Repository ocsigen/js_of_ocaml, pull requests merged in 2025-01, with the labels that each got.

#1782 Update GitHub Actions workflows
  .github/workflows/build-wasm_of_ocaml.yml
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .gitignore
  dune
  tools/ci_setup.ml
Labels: no changelog

#1780 Refine ECMASCRIPT.md
  ECMASCRIPT.md
Labels: documentation, no changelog

#1786 CI: restore workaround
  .github/workflows/build.yml
Labels: no changelog

#1781 Remove unused files
  .gitattributes
  .gitmodules
  api/dune
Labels: no changelog

#1789 CI: partial revert 1782, restore wasm ci
  .gitattributes
  .github/workflows/build-wasm_of_ocaml.yml
Labels: no changelog

#1771 Wasm_of_ocaml documentation
  README.md
  README_wasm_of_ocaml.md
  manual/menu.wiki
  manual/wasm_overview.wiki
  manual/wasm_runtime.wiki
Labels: documentation, no changelog, wasm

#1800 More win tests
  .github/workflows/build-wasm_of_ocaml.yml
  tools/ci_setup.ml
Labels: no changelog

#1806 CI: workaround opam pkg bug
  .github/workflows/build-wasm_of_ocaml.yml
  .github/workflows/build.yml
Labels: no changelog

#1807 CI: wasm tests are flaky on windows because of libuv
  .github/workflows/build-wasm_of_ocaml.yml
Labels: no changelog

#1803 Runtime: Add float16 support to bigarray
  CHANGES.md
  compiler/tests-jsoo/dune
  compiler/tests-jsoo/test_float16.expected
  compiler/tests-jsoo/test_float16.ml
  compiler/tests-ocaml/lib-bigarray/bigarrays.expected
  compiler/tests-ocaml/lib-bigarray/bigarrays.ml
  compiler/tests-ocaml/lib-bigarray/dune
  compiler/tests-ocaml/lib-bigarray/specialized.ml
  runtime/js/bigarray.js
  runtime/wasm/bigarray.wat
  runtime/wasm/hash.wat
  runtime/wasm/runtime.js
Labels: bug

#1812 Fix double-translation tests
  compiler/tests-jsoo/lib-effects-2/dune
Labels: no changelog

#1813 Add OCaml sys tests
  compiler/tests-ocaml/lib-sys/dune
  compiler/tests-ocaml/lib-sys/immediate64.ml
  compiler/tests-ocaml/lib-sys/rename.expected
  compiler/tests-ocaml/lib-sys/rename.ml
  runtime/js/fs_node.js
  runtime/wasm/fs.wat
  runtime/wasm/runtime.js
Labels: no changelog
