Repository ocsigen/js_of_ocaml, pull requests merged in 2025-04, with the labels that each got.

#1914 Ppx: cosmetic change, more control over uid generation order
  ppx/ppx_js/lib_internal/ppx_js_internal.ml
  ppx/ppx_js/tests/gen.mlt
Labels: no changelog

#1911 Add a debug option to keep wat files
  compiler/bin-wasm_of_ocaml/build_runtime.ml
  compiler/bin-wasm_of_ocaml/cmd_arg.ml
  compiler/bin-wasm_of_ocaml/cmd_arg.mli
  compiler/bin-wasm_of_ocaml/compile.ml
  compiler/bin-wasm_of_ocaml/link.ml
  compiler/bin-wasm_of_ocaml/link.mli
  compiler/bin-wasm_of_ocaml/wasm_of_ocaml.ml
Labels: no changelog, wasm

#1916 More extensive Wasm AST
  compiler/lib-wasm/code_generation.ml
  compiler/lib-wasm/curry.ml
  compiler/lib-wasm/gc_target.ml
  compiler/lib-wasm/generate.ml
  compiler/lib-wasm/initialize_locals.ml
  compiler/lib-wasm/tail_call.ml
  compiler/lib-wasm/wasm_ast.ml
  compiler/lib-wasm/wasm_link.ml
  compiler/lib-wasm/wasm_output.ml
  compiler/lib-wasm/wat_output.ml
Labels: no changelog, wasm

#1920 Use a specific runtime for CPS-based effects
  compiler/bin-wasm_of_ocaml/compile.ml
  compiler/bin-wasm_of_ocaml/dune
  compiler/bin-wasm_of_ocaml/gen/gen.ml
  compiler/lib-wasm/gc_target.ml
  compiler/lib-wasm/generate.ml
  runtime/wasm/dune
  runtime/wasm/effect.wat
  runtime/wasm/obj.wat
Labels: wasm

#1924 Compiler: make noop prims more explicit
  compiler/bin-js_of_ocaml/check_runtime.ml
  compiler/lib-wasm/generate.ml
  compiler/lib/generate.ml
  compiler/lib/parse_bytecode.ml
  runtime/js/stdlib.js
Labels: no changelog

#1909 Check wasmoo js runtime
  compiler/bin-wasm_of_ocaml/gen/dune
  compiler/bin-wasm_of_ocaml/gen/gen.ml
  compiler/lib/reserved.ml
  runtime/wasm/runtime.js
Labels: no changelog, wasm

#1900 Global flow analysis: performance improvements
  compiler/lib/code.ml
  compiler/lib/code.mli
  compiler/lib/driver.ml
  compiler/lib/global_flow.ml
Labels: no changelog

#1927 Benchmarks: move version-specific set-up from docker file to makefiles
  .dockerignore
  bench.Dockerfile
  benchmarks/Makefile
  benchmarks/benchmark-camlboy/Makefile
  benchmarks/benchmark-fiat-crypto/Makefile
  benchmarks/benchmark-ocamlc/Makefile
  benchmarks/benchmark-partial-render-table/Makefile
  benchmarks/report.ml
Labels: no changelog

#1931 Runtime compilation: fail if importing from unexpected modules
  compiler/bin-wasm_of_ocaml/compile.ml
  compiler/bin-wasm_of_ocaml/link_wasm.ml
  compiler/lib-wasm/runtime.ml
  compiler/lib-wasm/runtime.mli
  runtime/wasm/dune
Labels: no changelog, wasm

#1932 CI: pin setup-ocaml to avoid cygwin.3.6.1 issues
  .github/workflows/build-wasm_of_ocaml.yml
  .github/workflows/build.yml
Labels: no changelog

#1912 Optimization of primitives: some improvements
  CHANGES.md
  compiler/lib-wasm/gc_target.ml
  compiler/lib-wasm/generate.ml
  compiler/lib-wasm/target_sig.ml
  compiler/lib-wasm/wat_output.ml
  compiler/tests-compiler/test_string.ml
  runtime/js/compare.js
  runtime/js/ieee_754.js
  runtime/js/ints.js
  runtime/js/mlBytes.js
  runtime/js/prng.js
  runtime/wasm/float.wat
Labels: wasm, runtime, js

#1936 Benchmarks: report generated code size
  benchmarks/benchmark-fiat-crypto/Makefile
  benchmarks/benchmark-ocamlc/Makefile
  benchmarks/benchmark-partial-render-table/Makefile
  benchmarks/utils/compilation_metrics.ml
Labels: no changelog

#1938 Fix performance issue with Structure.is_merge_node
  compiler/lib/structure.ml
Labels: no changelog

#1940 JavaScript: fix incorrect simplification
  compiler/lib/js_traverse.ml
Labels: no changelog

#1941 Misc: reduce usage of polymorphic ops
  compiler/bin-js_of_ocaml/check_runtime.ml
  compiler/bin-wasm_of_ocaml/compile.ml
  compiler/lib-wasm/binaryen.ml
  compiler/lib-wasm/code_generation.ml
  compiler/lib-wasm/link.ml
  compiler/lib-wasm/wasm_link.ml
  compiler/lib-wasm/wasm_output.ml
  compiler/lib-wasm/wat_output.ml
  compiler/lib-wasm/wat_preprocess.ml
  compiler/lib-wasm/wat_preprocess.mli
  compiler/lib/code.ml
  compiler/lib/code.mli
  compiler/lib/config.ml
  compiler/lib/driver.ml
  compiler/lib/driver.mli
  compiler/lib/eval.ml
  compiler/lib/flow.ml
  compiler/lib/generate.ml
  compiler/lib/global_flow.ml
  compiler/lib/instr.ml
  compiler/lib/javascript.ml
  compiler/lib/javascript.mli
  compiler/lib/js_output.ml
  compiler/lib/js_simpl.ml
  compiler/lib/js_traverse.ml
  compiler/lib/link_js.ml
  compiler/lib/primitive.ml
  compiler/lib/stdlib.ml
  compiler/tests-js-parser/run.ml
Labels: no changelog

#1944 CI: fix for the latest setup-ocaml
  .github/workflows/build-wasm_of_ocaml.yml
  .github/workflows/build.yml
Labels: no changelog
