Repository ocsigen/js_of_ocaml, pull requests merged in 2025-03, with the labels that each got.

#1840 runtime(js): use es6 class
  CHANGES.md
  ECMASCRIPT.md
  runtime/js/bigarray.js
  runtime/js/fs_fake.js
  runtime/js/fs_node.js
  runtime/js/int64.js
  runtime/js/io.js
  runtime/js/marshal.js
  runtime/js/mlBytes.js
  runtime/js/nat.js
  runtime/js/sync.js
Labels: runtime

#1850 runtime(js): update constant imports to use `node:fs` module
  CHANGES.md
  runtime/js/fs_node.js
Labels: runtime

#1853 Misc: no subst
  dune-project
  js_of_ocaml-compiler.opam
  js_of_ocaml-compiler.opam.template
  js_of_ocaml-lwt.opam
  js_of_ocaml-lwt.opam.template
  js_of_ocaml-ppx.opam
  js_of_ocaml-ppx.opam.template
  js_of_ocaml-ppx_deriving_json.opam
  js_of_ocaml-ppx_deriving_json.opam.template
  js_of_ocaml-toplevel.opam
  js_of_ocaml-toplevel.opam.template
  js_of_ocaml-tyxml.opam
  js_of_ocaml-tyxml.opam.template
  js_of_ocaml.opam
  js_of_ocaml.opam.template
  wasm_of_ocaml-compiler.opam
  wasm_of_ocaml-compiler.opam.template
Labels: no changelog

#1851 Update ECMASCRIPT.md
  ECMASCRIPT.md
Labels: documentation, no changelog, runtime

#1858 Refactor benchmark script and support current-bench
  benchmarks/Makefile
  benchmarks/common.ml
  benchmarks/dune
  benchmarks/report.ml
  benchmarks/run.ml
Labels: no changelog

#1861 runtime(js): fix useOptionalChain
  biome.json
  runtime/js/compare.js
  runtime/js/dynlink.js
  runtime/js/effect.js
  runtime/js/fs.js
  runtime/js/fs_fake.js
  runtime/js/hash.js
  runtime/js/jslib.js
  runtime/js/obj.js
  runtime/js/sys.js
  runtime/wasm/runtime.js
Labels: no changelog, runtime

#1872 Json.output improvements
  CHANGES.md
  lib/js_of_ocaml/json.ml
  lib/tests/dune.inc
  lib/tests/gen-rules/gen.ml
  lib/tests/test_json.ml
Labels: wasm

#1876 Wasm runtime: add stubs for caml_create_file and caml_mount_autoload
  runtime/wasm/fs.wat
Labels: no changelog, wasm, runtime

#1878 Fix Dom_html.Keyboard_code.of_event
  CHANGES.md
  lib/js_of_ocaml/dom_html.ml
Labels: bug

#1890 Misc: makefile target for formatting and linting js
  Makefile
Labels: no changelog

#1881 Wasm runtime: keep track of backtrace status
  CHANGES.md
  runtime/wasm/backtrace.wat
  runtime/wasm/runtime.js
Labels: wasm, runtime

#1891 Effects: store the tail of the fiber stack in the continuation
  runtime/js/effect.js
Labels: no changelog

#1877 Fix jsoo_mkcmis
  CHANGES.md
  toplevel/bin/jsoo_mkcmis.ml
  toplevel/test/dune
  toplevel/test/test_toplevel.expected
  toplevel/test/test_toplevel1.ml
  toplevel/test/test_toplevel2.ml
Labels: bug

#1884 Wasm_of_ocaml: do not minify twice the always-included JavaScript
  compiler/bin-wasm_of_ocaml/compile.ml
  compiler/lib-wasm/link.ml
  compiler/lib/driver.ml
  compiler/lib/driver.mli
Labels: no changelog, wasm

#1893 Small cleanup
  compiler/bin-js_of_ocaml/compile.ml
  compiler/bin-wasm_of_ocaml/preprocess.ml
  compiler/lib-wasm/binaryen.ml
  compiler/lib-wasm/link.ml
  compiler/lib/link_js.ml
  compiler/lib/parse_js.ml
  compiler/lib/source_map.ml
  compiler/lib/source_map.mli
  compiler/lib/stdlib.ml
  compiler/tests-compiler/util/util.ml
  compiler/tests-sourcemap/dump_sourcemap.ml
  tools/sourcemap/jsoo_sourcemap.ml
  toplevel/bin/jsoo_mkcmis.ml
Labels: no changelog

#1895 Fix current-bench benchmark config for JSOO time
  benchmarks/report-jsoo-cb.config
Labels: no changelog

#1896 Compiler: cleanup an old TODO
  compiler/ppx/ppx_optcomp_light.ml
Labels: no changelog

#1902 Misc: reduce deps
  .github/workflows/build-wasm_of_ocaml.yml
  .github/workflows/build.yml
  CONTRIBUTING.md
  dune-project
  js_of_ocaml-toplevel.opam
  manual/contribute.wiki
  tools/ci_setup.ml
  toplevel/examples/server/dune
Labels: no changelog

#1903 Some cleanup for the CI
  .github/workflows/build-wasm_of_ocaml.yml
  tools/ci_setup.ml
Labels: no changelog

#1904 Fix bound check for empty float array
  CHANGES.md
  compiler/lib-wasm/gc_target.ml
  compiler/lib-wasm/generate.ml
  compiler/lib-wasm/target_sig.ml
  compiler/tests-wasm_of_ocaml/dune
  compiler/tests-wasm_of_ocaml/gh1904.ml
Labels: wasm
